project_id = "eapbulrifjyhlxpsydin"

[functions.admin-save-exam]
verify_jwt = false

[functions.create-tax-payment]
verify_jwt = false

[functions.verify-tax-payment]
verify_jwt = false

[functions.generate-exam-result-pdf]
verify_jwt = false